### ISSUE TITLE
depedency error on build

### ISSUE THREAD

**Issue by kaiminator** [FreddyFFM/shellyupdater#11]
ERROR: Cannot install -r requirements.txt (line 13) and urllib3==1.26.5 because these package versions have conflicting dependencies.

The conflict is caused by:
    The user requested urllib3==1.26.5
    requests 2.24.0 depends on urllib3!=1.25.0, !=1.25.1, <1.26 and >=1.21.1

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/user_guide/#fixing-conflicting-dependencies
The command '/bin/sh -c cd /home/updater && pip3 install -r requirements.txt' returned a non-zero code: 1
ERROR: Service 'shellyupdater' failed to build : Build failed

**Comment by kaiminator** [comment]
Resolution:

edit ./shellyupdater/requirements.txt 

-> change requests==2.24.0 to requests==2.25.1

**Comment by FreddyFFM** [comment]
Thanks for commenting with the solution. Will try to update it asap.
