### ISSUE TITLE
Error when opening website

### ISSUE THREAD

**Issue by FlorianDessloch** [FreddyFFM/shellyupdater#2]
I get the following error when opening the website:

Environment:

Request Method: GET
Request URL: http://192.168.102.11:7000/

Django Version: 2.2.13
Python Version: 3.5.9
Installed Applications:
['django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'home',
 'updates',
 'setter']
Installed Middleware:
['django.middleware.security.SecurityMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware']

Traceback:

File "/usr/local/lib/python3.5/site-packages/django/core/handlers/exception.py" in inner
  34.             response = get_response(request)

File "/usr/local/lib/python3.5/site-packages/django/core/handlers/base.py" in _get_response
  115.                 response = self.process_exception_by_middleware(e, request)

File "/usr/local/lib/python3.5/site-packages/django/core/handlers/base.py" in _get_response
  113.                 response = wrapped_callback(request, *callback_args, **callback_kwargs)

File "/usr/local/lib/python3.5/site-packages/django/views/generic/base.py" in view
  71.             return self.dispatch(request, *args, **kwargs)

File "/usr/local/lib/python3.5/site-packages/django/views/generic/base.py" in dispatch
  97.         return handler(request, *args, **kwargs)

File "/home/updater/shellyupdater/home/views.py" in get
  29.         shelly_min_battery = Shellies.objects.filter(shelly2infos__shelly_battery_percent__isnull=False).order_by('shelly2infos__shelly_battery_percent')[0]

File "/usr/local/lib/python3.5/site-packages/django/db/models/query.py" in __getitem__
  309.         return qs._result_cache[0]

Exception Type: IndexError at /
Exception Value: list index out of range

**Comment by FreddyFFM** [comment]
Did you update the sources with a git pull and rebuild the container?
With my last commit I already fixed some Exception issues

**Comment by FlorianDessloch** [comment]
Yes, I did

**Comment by FreddyFFM** [comment]
I did a major update/new release. So please do a new git pull or download release.
I added more error-handling and tested the initial start on clean environments.
